const data = [
	{
		id: "a8831054-bab5-4449-84ca-8f87323b4652",
		link: null,
		name: "Scalloped Potatoes",
		page: 264,
		time: "1 hr 30 mins",
		image: null,
		title: "Tasty Ultimate",
		author: "Tasty",
		cuisine: "American",
		protein: "Veggie",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "dba4b804-cd4d-4959-a8c5-33e4d71127b1",
		link: null,
		name: "Carne en su Jugo",
		page: 251,
		time: "2 hrs",
		image: null,
		title: "Mi Cocina",
		author: "Rick Martínez",
		cuisine: "Mexican",
		protein: "Beef",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "01eea6b7-85a2-4d0b-b9be-f43ed892a8a2",
		link: null,
		name: "Spiced Chicken Legs with Garlic Crunch-Crumbs",
		page: 142,
		time: "3 hrs 30 mins",
		image: null,
		title: "That Sounds So Good",
		author: "Carla Lalli Music",
		cuisine: "Italian",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "01ef2577-e81a-4215-954d-aadea2100190",
		link: null,
		name: "Pasta Aglio e Olio",
		page: 29,
		time: "30 mins",
		image: null,
		title: "Binging with Babish",
		author: "Andrew Rea",
		cuisine: "Italian",
		protein: "Veggie",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "0c53b456-f26b-4392-9758-7f0049a38763",
		link: null,
		name: "Herbed Chicken Thighs",
		page: 90,
		time: "45 mins",
		image: null,
		title: "Tasty Ultimate",
		author: "Tasty",
		cuisine: "American",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "276be57e-c3d9-42c1-a488-e66119749236",
		link: null,
		name: "Arroz con Pollo",
		page: 306,
		time: "3 hrs",
		image: null,
		title: "Puerto Rican Cookery",
		author: "Carmen Aboy Valldejuli",
		cuisine: "Criollo",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "ca52ac63-3bbf-4ca8-9994-145cfbc3f753",
		link: null,
		name: "Cochinita Pibil",
		page: 149,
		time: "6 hrs",
		image: null,
		title: "Mi Cocina",
		author: "Rick Martínez",
		cuisine: "Mexican",
		protein: "Pork",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "673242d0-d68f-42ef-901b-49b908bdeb37",
		link: null,
		name: "Prosciutto-Wrapped Stuffed Chicken Breasts",
		page: 232,
		time: "1 hr",
		image: null,
		title: "Cravings",
		author: "Chrissy Teigen",
		cuisine: "American",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=kbg_CgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "a00a4bba-f970-470d-9d41-c0f02a218ab7",
		link: null,
		name: "Beef Burgundy",
		page: 83,
		time: "5 hrs",
		image: null,
		title: "Binging with Babish",
		author: "Andrew Rea",
		cuisine: "French",
		protein: "Beef",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "6b122d65-6c0b-43d5-aead-80d5af0b9a7d",
		link: null,
		name: "Char Siu",
		page: 290,
		time: "4 hrs",
		image: null,
		title: "Nom Nom Paleo",
		author: "Michelle Tam",
		cuisine: "Asian",
		protein: "Pork",
		cover_image:
			"http://books.google.com/books/content?id=P4gzEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "aa02a0cd-295d-4606-b389-e9fdca803e89",
		link: null,
		name: "Spicy Tuna Cakes",
		page: 183,
		time: "45 mins",
		image: null,
		title: "Nom Nom Paleo",
		author: "Michelle Tam",
		cuisine: "Asian",
		protein: "Seafood",
		cover_image:
			"http://books.google.com/books/content?id=4VfQAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "dcff7816-7743-4e41-ac93-a8302bc0c0c5",
		link: null,
		name: "Seared Pork Chops with Mushroom & White Wine Sauce",
		page: 272,
		time: "30 mins",
		image: null,
		title: "Tasty Ultimate",
		author: "Tasty",
		cuisine: "American",
		protein: "Pork",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "5139e743-005a-4b84-b27c-7382499e0185",
		link: null,
		name: "Rosemary Chicken with Potatoes",
		page: 101,
		time: "1 hr",
		image: null,
		title: "5-Ingredient Cooking for Two: 100 Recipes Portioned for Pairs",
		author: "Robin Donovan",
		cuisine: "American",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=d_aIxQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "8bff0504-3b2d-47bc-ac4b-5f496740c12d",
		link: null,
		name: "Sheet Pan Chicken with Tomatoes and Chickpeas",
		page: 197,
		time: "3 hrs",
		image: null,
		title: "That Sounds So Good",
		author: "Carla Lalli Music",
		cuisine: "Italian",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Oven",
	},
	{
		id: "edb84a7e-0f4f-40ea-938b-b193aeaa4406",
		link: null,
		name: "Carne Guisada",
		page: 83,
		time: "3 hrs 30 mins",
		image: null,
		title: "Puerto Rican Cookery",
		author: "Carmen Aboy Valldejuli",
		cuisine: "Criollo",
		protein: "Beef",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "6a7711f9-b468-4641-ac1b-7cb9914be84d",
		link: "https://www.youtube.com/watch?v=Ia69K80NEAA",
		name: "Spinach and Artichoke Lasagna",
		page: null,
		time: "3 hrs 30 mins",
		image: "https://i.ytimg.com/vi/Ia69K80NEAA/sddefault.jpg",
		title: null,
		author: null,
		cuisine: "Italian",
		protein: "Veggie",
		cover_image: null,
		cooking_type: "Oven",
	},
	{
		id: "d56ad4cb-f9ef-4428-8d5e-a9dad8184d17",
		link: null,
		name: "Aguachile",
		page: 242,
		time: "15 mins",
		image: null,
		title: "Mi Cocina",
		author: "Rick Martínez",
		cuisine: "Mexican",
		protein: "Seafood",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stir-Fry",
	},
	{
		id: "0380cafd-6a95-4d8e-a9ae-67eb678a721d",
		link: "https://www.youtube.com/watch?v=gWipuXKTYkw",
		name: "Mushroom Pepper Basil Pasta (OPP)",
		page: null,
		time: "1 hr",
		image: "https://i.ytimg.com/vi/gWipuXKTYkw/sddefault.jpg",
		title: null,
		author: null,
		cuisine: "Italian",
		protein: "Veggie",
		cover_image: null,
		cooking_type: "Stovetop",
	},
	{
		id: "393ae304-8218-4a27-bf5d-b6a114e88249",
		link: null,
		name: "Super Tuna Melts",
		page: 228,
		time: "25 mins",
		image: null,
		title: "Cravings",
		author: "Chrissy Teigen",
		cuisine: "American",
		protein: "Seafood",
		cover_image:
			"http://books.google.com/books/content?id=kbg_CgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "eced8c65-c1cf-4691-917d-6473b74a17f3",
		link: null,
		name: "Sweet Potato Hash",
		page: 152,
		time: "15 mins",
		image: null,
		title: "Nom Nom Paleo",
		author: "Michelle Tam",
		cuisine: "American",
		protein: "Veggie",
		cover_image:
			"http://books.google.com/books/content?id=4VfQAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "cc59bdfb-40a1-4ded-84b5-ce3f39ed7a01",
		link: null,
		name: "Sancocho",
		page: 47,
		time: "3 hrs",
		image: null,
		title: "Puerto Rican Cookery",
		author: "Carmen Aboy Valldejuli",
		cuisine: "Criollo",
		protein: "Beef",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "0373407c-b663-4fd9-bf33-fa1b088ae652",
		link: null,
		name: "Eggs in Purgatory",
		page: 99,
		time: "30 mins",
		image: null,
		title: "That Sounds So Good",
		author: "Carla Lalli Music",
		cuisine: "Italian",
		protein: "Veggie",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "31b74312-afb9-4377-8896-c8a773d8f97d",
		link: null,
		name: "Chef's Special",
		page: 181,
		time: "1 hr",
		image: null,
		title: "Binging with Babish",
		author: "Andrew Rea",
		cuisine: "Criollo",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "e8a9973f-a7a1-4cdb-a2f4-34f816e90208",
		link: null,
		name: "Pasta with Chicken, Tomatoes, and Feta",
		page: 112,
		time: "25 mins",
		image: null,
		title: "5-Ingredient Cooking for Two: 100 Recipes Portioned for Pairs",
		author: "Robin Donovan",
		cuisine: "Italian",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=d_aIxQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Stovetop",
	},
	{
		id: "0fe36618-3fe7-4d27-b71d-8072232f622f",
		link: null,
		name: "Pan Chicken with Burst Tomato Sauce",
		page: 111,
		time: "30 mins",
		image: null,
		title: "That Sounds So Good",
		author: "Carla Lalli Music",
		cuisine: "Italian",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cooking_type: "Stir-Fry",
	},
	{
		id: "64a4cb5c-828e-40dd-8acf-014395818c7e",
		link: null,
		name: "Sopa de Pollo con Vegetales",
		page: 44,
		time: "1 hr 30 mins",
		image: null,
		title: "Puerto Rican Cookery",
		author: "Carmen Aboy Valldejuli",
		cuisine: "Criollo",
		protein: "Chicken",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cooking_type: "Stovetop",
	},
];

const filterData = [
	[
		"cuisine",
		"African, American, Asian, Criollo, French, German, Indian, Italian, Mediterranean, Mexican, Southern, Spanish",
	],
	["protein", "Beef, Chicken, Pork, Seafood, Turkey, Veggie"],
	["cookingType", "Air Fryer, Oven, Stew, Stir-Fry, Stovetop"],
];

export default { data, filterData };
