const data = [
	{
		author: "Rick Martínez",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Mexican",
		id: "d56ad4cb-f9ef-4428-8d5e-a9dad8184d17",
		image: null,
		link: null,
		name: "Aguachile",
		page: 242,
		protein: "Seafood",
		time: "15 mins",
		title: "Mi Cocina",
	},
	{
		author: null,
		cooking_type: "Air Fryer",
		cover_image: null,
		cuisine: "American",
		id: "8a5215ca-69df-4f4b-bf3a-a6e20c38e725",
		image: "https://knowseafood.com/cdn/shop/articles/AdobeStock_104451183.jpg?v=1664372341",
		link: "https://knowseafood.com/blogs/recipes/air-fried-mahi-mahi-bites",
		name: "Air Fried Mahi Mahi Bites",
		page: null,
		protein: "Seafood",
		time: "15 mins",
		title: null,
	},
	{
		author: "Carmen Aboy Valldejuli",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "Criollo",
		id: "276be57e-c3d9-42c1-a488-e66119749236",
		image: null,
		link: null,
		name: "Arroz con Pollo",
		page: 306,
		protein: "Chicken",
		time: "3 hrs",
		title: "Puerto Rican Cookery",
	},
	{
		author: "Andrew Rea",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "French",
		id: "a00a4bba-f970-470d-9d41-c0f02a218ab7",
		image: null,
		link: null,
		name: "Beef Burgundy",
		page: 83,
		protein: "Beef",
		time: "5 hrs",
		title: "Binging with Babish",
	},
	{
		author: "Carmen Aboy Valldejuli",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "Criollo",
		id: "edb84a7e-0f4f-40ea-938b-b193aeaa4406",
		image: null,
		link: null,
		name: "Carne Guisada",
		page: 83,
		protein: "Beef",
		time: "3 hrs 30 mins",
		title: "Puerto Rican Cookery",
	},
	{
		author: "Rick Martínez",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Mexican",
		id: "dba4b804-cd4d-4959-a8c5-33e4d71127b1",
		image: null,
		link: null,
		name: "Carne en su Jugo",
		page: 251,
		protein: "Beef",
		time: "2 hrs",
		title: "Mi Cocina",
	},
	{
		author: "Michelle Tam",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=P4gzEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Asian",
		id: "6b122d65-6c0b-43d5-aead-80d5af0b9a7d",
		image: null,
		link: null,
		name: "Char Siu",
		page: 290,
		protein: "Pork",
		time: "4 hrs",
		title: "Nom Nom Paleo",
	},
	{
		author: "Andrew Rea",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Criollo",
		id: "31b74312-afb9-4377-8896-c8a773d8f97d",
		image: null,
		link: null,
		name: "Chef's Special",
		page: 181,
		protein: "Chicken",
		time: "1 hr",
		title: "Binging with Babish",
	},
	{
		author: "Rick Martínez",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=Bpo7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Mexican",
		id: "ca52ac63-3bbf-4ca8-9994-145cfbc3f753",
		image: null,
		link: null,
		name: "Cochinita Pibil",
		page: 149,
		protein: "Pork",
		time: "6 hrs",
		title: "Mi Cocina",
	},
	{
		author: "Carla Lalli Music",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Italian",
		id: "0373407c-b663-4fd9-bf33-fa1b088ae652",
		image: null,
		link: null,
		name: "Eggs in Purgatory",
		page: 99,
		protein: "Veggie",
		time: "30 mins",
		title: "That Sounds So Good",
	},
	{
		author: "Tasty",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "0c53b456-f26b-4392-9758-7f0049a38763",
		image: null,
		link: null,
		name: "Herbed Chicken Thighs",
		page: 90,
		protein: "Chicken",
		time: "45 mins",
		title: "Tasty Ultimate",
	},
	{
		author: null,
		cooking_type: "Stovetop",
		cover_image: null,
		cuisine: "Italian",
		id: "0380cafd-6a95-4d8e-a9ae-67eb678a721d",
		image: "https://i.ytimg.com/vi/gWipuXKTYkw/sddefault.jpg",
		link: "https://www.youtube.com/watch?v=gWipuXKTYkw",
		name: "Mushroom Pepper Basil Pasta (OPP)",
		page: null,
		protein: "Veggie",
		time: "1 hr",
		title: null,
	},
	{
		author: "Carla Lalli Music",
		cooking_type: "Stir-Fry",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Italian",
		id: "0fe36618-3fe7-4d27-b71d-8072232f622f",
		image: null,
		link: null,
		name: "Pan Chicken with Burst Tomato Sauce",
		page: 111,
		protein: "Chicken",
		time: "30 mins",
		title: "That Sounds So Good",
	},
	{
		author: "Andrew Rea",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=I5KzDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Italian",
		id: "01ef2577-e81a-4215-954d-aadea2100190",
		image: null,
		link: null,
		name: "Pasta Aglio e Olio",
		page: 29,
		protein: "Veggie",
		time: "30 mins",
		title: "Binging with Babish",
	},
	{
		author: "Robin Donovan",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=d_aIxQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "Italian",
		id: "e8a9973f-a7a1-4cdb-a2f4-34f816e90208",
		image: null,
		link: null,
		name: "Pasta with Chicken, Tomatoes, and Feta",
		page: 112,
		protein: "Chicken",
		time: "25 mins",
		title: "5-Ingredient Cooking for Two: 100 Recipes Portioned for Pairs",
	},
	{
		author: "Chrissy Teigen",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=kbg_CgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "673242d0-d68f-42ef-901b-49b908bdeb37",
		image: null,
		link: null,
		name: "Prosciutto-Wrapped Stuffed Chicken Breasts",
		page: 232,
		protein: "Chicken",
		time: "1 hr",
		title: "Cravings",
	},
	{
		author: "Robin Donovan",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=d_aIxQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "American",
		id: "5139e743-005a-4b84-b27c-7382499e0185",
		image: null,
		link: null,
		name: "Rosemary Chicken with Potatoes",
		page: 101,
		protein: "Chicken",
		time: "1 hr",
		title: "5-Ingredient Cooking for Two: 100 Recipes Portioned for Pairs",
	},
	{
		author: "Carmen Aboy Valldejuli",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "Criollo",
		id: "cc59bdfb-40a1-4ded-84b5-ce3f39ed7a01",
		image: null,
		link: null,
		name: "Sancocho",
		page: 47,
		protein: "Beef",
		time: "3 hrs",
		title: "Puerto Rican Cookery",
	},
	{
		author: "Tasty",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "a8831054-bab5-4449-84ca-8f87323b4652",
		image: null,
		link: null,
		name: "Scalloped Potatoes",
		page: 264,
		protein: "Veggie",
		time: "1 hr 30 mins",
		title: "Tasty Ultimate",
	},
	{
		author: "Tasty",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=OpZbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "dcff7816-7743-4e41-ac93-a8302bc0c0c5",
		image: null,
		link: null,
		name: "Seared Pork Chops with Mushroom & White Wine Sauce",
		page: 272,
		protein: "Pork",
		time: "30 mins",
		title: "Tasty Ultimate",
	},
	{
		author: "Carla Lalli Music",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Italian",
		id: "8bff0504-3b2d-47bc-ac4b-5f496740c12d",
		image: null,
		link: null,
		name: "Sheet Pan Chicken with Tomatoes and Chickpeas",
		page: 197,
		protein: "Chicken",
		time: "3 hrs",
		title: "That Sounds So Good",
	},
	{
		author: "Carmen Aboy Valldejuli",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=zVk-AQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
		cuisine: "Criollo",
		id: "64a4cb5c-828e-40dd-8acf-014395818c7e",
		image: null,
		link: null,
		name: "Sopa de Pollo con Vegetales",
		page: 44,
		protein: "Chicken",
		time: "1 hr 30 mins",
		title: "Puerto Rican Cookery",
	},
	{
		author: "Carla Lalli Music",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=7QkTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Italian",
		id: "01eea6b7-85a2-4d0b-b9be-f43ed892a8a2",
		image: null,
		link: null,
		name: "Spiced Chicken Legs with Garlic Crunch-Crumbs",
		page: 142,
		protein: "Chicken",
		time: "3 hrs 30 mins",
		title: "That Sounds So Good",
	},
	{
		author: "Michelle Tam",
		cooking_type: "Oven",
		cover_image:
			"http://books.google.com/books/content?id=4VfQAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "Asian",
		id: "aa02a0cd-295d-4606-b389-e9fdca803e89",
		image: null,
		link: null,
		name: "Spicy Tuna Cakes",
		page: 183,
		protein: "Seafood",
		time: "45 mins",
		title: "Nom Nom Paleo",
	},
	{
		author: null,
		cooking_type: "Oven",
		cover_image: null,
		cuisine: "Italian",
		id: "6a7711f9-b468-4641-ac1b-7cb9914be84d",
		image: "https://i.ytimg.com/vi/Ia69K80NEAA/sddefault.jpg",
		link: "https://www.youtube.com/watch?v=Ia69K80NEAA",
		name: "Spinach and Artichoke Lasagna",
		page: null,
		protein: "Veggie",
		time: "3 hrs 30 mins",
		title: null,
	},
	{
		author: "Chrissy Teigen",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=kbg_CgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "393ae304-8218-4a27-bf5d-b6a114e88249",
		image: null,
		link: null,
		name: "Super Tuna Melts",
		page: 228,
		protein: "Seafood",
		time: "25 mins",
		title: "Cravings",
	},
	{
		author: "Michelle Tam",
		cooking_type: "Stovetop",
		cover_image:
			"http://books.google.com/books/content?id=4VfQAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
		cuisine: "American",
		id: "eced8c65-c1cf-4691-917d-6473b74a17f3",
		image: null,
		link: null,
		name: "Sweet Potato Hash",
		page: 152,
		protein: "Veggie",
		time: "15 mins",
		title: "Nom Nom Paleo",
	},
];

const filterData = [
	["cuisine","African,American,Asian,Criollo,French,German,Indian,Italian,Mediterranean,Mexican,Southern,Spanish"],
	["protein","Beef,Chicken,Pork,Seafood,Turkey,Veggie"],
	["cookingType","AirFryer,Oven,Stew,Stir-Fry,Stovetop"],
];

export default { data, filterData };
